#!/bin/bash
set -e

echo "Starting system setup..."

mkdir -p /opt/gk/

echo "Registering services..."
systemctl enable gk-server
systemctl start gk-server
systemctl enable gk-port-watcher
systemctl start gk-port-watcher

echo "Installation completed!"
