import os

class Config:
    SQLALCHEMY_DATABASE_URI = os.getenv("DATABASE_URL", "sqlite:///ports.db")
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    API_TOKEN = os.getenv("API_TOKEN", "supersecrettoken")

    SINGLE_PORT_ALLOCATION_START = int(os.getenv("SINGLE_PORT_ALLOCATION_START", 8000))
    SINGLE_PORT_ALLOCATION_END = int(os.getenv("SINGLE_PORT_ALLOCATION_END", 10000))

    PORT_RANGE_ALLOCATION_START = int(os.getenv("PORT_RANGE_ALLOCATION_START", 12000))
    PORT_RANGE_ALLOCATION_END = int(os.getenv("PORT_RANGE_ALLOCATION_END", 14000))
