#!/bin/bash
set -e

echo "Removing services..."
systemctl stop gk-port-watcher || true
systemctl disable gk-port-watcher || true
systemctl stop gk-server || true
systemctl disable gk-server || true

systemctl daemon-reload || true

# echo "Removing database..."
# rm -rf /opt/gk/

echo "Removal completed!"
