import click
from sys import exit
from services import RedisContainerService, MongoContainerService
from services import OpenFaaSContainerService
from exceptions import DockerDaemonException, DockerException
from time import sleep


@click.group()
@click.pass_context
def logs(ctx):
    """
    Manage container logs.

    The das-cli logs command allows you to display logs of various services.
    This command retrieves logs generated by specific services and provides insights into their operations, including information about connections, queries, executions, and errors.
    """

    global config

    config = ctx.obj["config"]


@logs.command()
def das():
    """
    Display logs for das.

    The das-cli logs das command displays the logs of the DAS service.
    This command retrieves the logs generated by the DAS service, which are typically located in
    the /tmp/das.log file.

    .SH EXAMPLES

    Display logs of the DAS service.

    $ das-cli logs das
    """
    try:
        with open("/tmp/das.log", "r") as file:
            while True:
                line = file.readline()
                if not line:
                    sleep(0.1)
                    continue
                click.echo(line, nl=False)
    except KeyboardInterrupt:
        click.secho("Interrupted. Exiting...", fg="red")
    except FileNotFoundError:
        click.secho("No logs to show up here", fg="yellow")


@logs.command()
def faas():
    """
    Display logs for OpenFaaS services.

    The das-cli logs faas command displays the logs of the OpenFaaS service.
    This command retrieves the logs generated by the OpenFaaS service, which may include information about function executions, deployments, and errors.

    .SH EXAMPLES

    Display logs of the OpenFaaS service.

    $ das-cli logs faas
    """

    openfaas_container_name = config.get("openfaas.container_name")
    mongodb_container_name = config.get("mongodb.container_name")
    redis_container_name = config.get("redis.container_name")

    try:
        openfaas_service = OpenFaaSContainerService(
            openfaas_container_name,
            redis_container_name,
            mongodb_container_name,
        )

        openfaas_service.logs()
    except DockerException as e:
        click.secho(str(e), fg="red")
        click.secho("You need to run the server with command 'db start'", fg="red")
        exit(1)
    except DockerDaemonException as e:
        click.secho(f"{str(e)}\n", fg="red")
        exit(1)


@logs.command()
def mongodb():
    """
    Display logs of the MongoDB service.

    The das-cli logs mongodb command displays the logs of the MongoDB service.
    This command retrieves the logs generated by the MongoDB service, which may include information about database connections, queries, and errors.

    .SH EXAMPLES

    Display logs of the MongoDB service.

    $ das-cli logs mongodb
    """

    mongodb_container_name = config.get("mongodb.container_name")

    try:
        mongodb_service = MongoContainerService(mongodb_container_name)

        mongodb_service.logs()
    except DockerException as e:
        click.secho(str(e), fg="red")
        click.secho("You need to run the server with command 'db start'", fg="red")
        exit(1)
    except DockerDaemonException as e:
        click.secho(f"{str(e)}\n", fg="red")
        exit(1)


@logs.command()
def redis():
    """
    Display logs for Redis.

    The das-cli logs redis command displays the logs of the Redis service.
    This command retrieves the logs generated by the Redis service, which may include information about connections, commands, and errors.

    EXAMPLES

    Display logs of the Redis service.

    $ das-cli logs redis
    """
    redis_container_name = config.get("redis.container_name")

    try:
        redis_service = RedisContainerService(redis_container_name)

        redis_service.logs()
    except DockerException as e:
        click.secho(str(e), fg="red")
        click.secho("You need to run the server with command 'db start'", fg="red")
        exit(1)
    except DockerDaemonException as e:
        click.secho(f"{str(e)}\n", fg="red")
        exit(1)
