# PATHS

SECRETS_PATH = "~/.das/config.json"
ACTIVE_SERVICES_PATH = "~/.das/containers.json"

# SERVICES

REDIS_IMAGE_NAME = "redis"
REDIS_IMAGE_VERSION = "7.2.3-alpine"

MONGODB_IMAGE_NAME = "mongo"
MONGODB_IMAGE_VERSION = "6.0.13-jammy"

CANONICAL_LOAD_IMAGE_NAME = "levisingnet/canonical-load"
CANONICAL_LOAD_IMAGE_VERSION = "latest"

METTA_PARSER_IMAGE_NAME = "trueagi/das"
METTA_PARSER_IMAGE_VERSION = "v0.1.1-toolbox"

CANONICAL_LOAD_BETA_IMAGE_NAME = "trueagi/das"
CANONICAL_LOAD_BETA_IMAGE_VERSION = "v0.1.1-toolbox"
