HELP_DAS_LOGS = """
NAME

    logs das - Display logs for the DAS service

SYNOPSIS

    das-cli logs das

DESCRIPTION

    Displays the logs of the DAS service.
    This command reads logs from the log file used by the DAS core process, typically located at `/tmp/das.log`.
    Logs will stream in real-time until the user exits with Ctrl+C.

EXAMPLES

    Display logs of the DAS service:

        das-cli logs das
"""

SHORT_HELP_DAS_LOGS = "Display logs for das."

HELP_MONGODB = """
NAME

    logs mongodb - Display logs for the MongoDB service

SYNOPSIS

    das-cli logs mongodb

DESCRIPTION

    Displays logs generated by the MongoDB container.
    This includes database events such as connections, queries, and internal errors.
    The MongoDB container must be running for logs to be available.

EXAMPLES

    Display logs of the MongoDB service:

        das-cli logs mongodb
"""

SHORT_HELP_MONGODB = "Display logs of the MongoDB service."

HELP_REDIS = """
NAME

    logs redis - Display logs for the Redis service

SYNOPSIS

    das-cli logs redis

DESCRIPTION

    Displays logs generated by the Redis container.
    These logs include cache operations, connections, key access patterns, and error messages.
    The Redis container must be running for logs to be available.

EXAMPLES

    Display logs of the Redis service:

        das-cli logs redis
"""

SHORT_HELP_REDIS = "Display logs for Redis."

HELP_AB = """
'das-cli logs attention-broker' displays the logs of the Attention Broker service.
This command retrieves the logs generated by the Attention Broker, which may include information about message routing, broker events, and errors.

.SH EXAMPLES

Display logs of the Attention Broker service.

$ das-cli logs attention-broker
"""

SHORT_HELP_AB = "Display logs for the Attention Broker service"

HELP_QA = """
'das-cli logs query-agent' displays the logs of the Query Agent service.
This command retrieves the logs generated by the Query Agent, which may include information about query processing, agent events, and errors.

.SH EXAMPLES

Display logs of the Query Agent service.

$ das-cli logs query-agent
"""

SHORT_HELP_QA = "Display logs for the Query Agent service"

HELP_LCA = """
'das-cli logs link-creation-agent' displays the logs of the Link Creation Agent service.
This command retrieves the logs generated by the Link Creation Agent, which may include information about link creation processes, agent events, and errors.

.SH EXAMPLES

Display logs of the Link Creation Agent service.

$ das-cli logs link-creation-agent
"""

SHORT_HELP_LCA = "Display logs for the Link Creation Agent service"

HELP_IA = """
'das-cli logs inference-agent' displays the logs of the Inference Agent service.
This command retrieves the logs generated by the Inference Agent, which may include information about inference processes, agent events, and errors.

.SH EXAMPLES

Display logs of the Inference Agent service.

$ das-cli logs inference-agent
"""

SHORT_HELP_IA = "Display logs for the Inference Agent service."

HELP_EA = """
'das-cli logs evolution-agent' displays the logs of the Evolution Agent service.
This command retrieves the logs generated by the Evolution Agent, which may include information about evolution processes, agent events, and errors.

.SH EXAMPLES

Display logs of the Evolution Agent service.

$ das-cli logs evolution-agent
"""

SHORT_HELP_EA = "Display logs for the Evolution Agent service"

HELP_CB = """
'das-cli logs context-broker' displays the logs of the Context Broker service.
This command retrieves the logs generated by the Context Broker, which may include information about evolution processes, agent events, and errors.

.SH EXAMPLES

Display logs of the Context Broker service.

$ das-cli logs context-broker
"""

SHORT_HELP_CB = "Display logs for the Context Broker service"

HELP_LOGS = """
NAME

    logs - Manage container logs

SYNOPSIS

    das-cli logs <service>

DESCRIPTION

    Displays logs for services managed by the DAS CLI.
    These logs provide insight into operations, errors, and runtime behavior.

COMMANDS

    das-cli logs das                        Logs from the DAS core
    das-cli logs mongodb                    Logs from the MongoDB database
    das-cli logs redis                      Logs from the Redis cache
    das-cli logs attention-broker           Logs from the Attention Broker service
    das-cli logs query-agent                Logs from the Query Agent service
    das-cli logs link-creation-agent        Logs from the Link Creation Agent service
    das-cli logs inference-agent            Logs from the Inference Agent service
    das-cli logs evolution-agent            Logs from the Evolution Agent service
    das-cli logs context-broker             Logs from the Context Broker service

EXAMPLES

    Display logs from the DAS core:

        das-cli logs das

    Display logs from MongoDB:

        das-cli logs mongodb

    Display logs from Redis:

        das-cli logs redis

    Display logs from the Attention Broker service:

        das-cli logs attention-broker

    Display logs from the Query Agent service:

        das-cli logs query-agent

    Display logs from the Link Creation Agent service:

        das-cli logs link-creation-agent

    Display logs from the Inference Agent service:

        das-cli logs inference-agent

    Display logs from the Evolution Agent service:

        das-cli logs evolution-agent

    Display logs from the Context Broker service:

        das-cli logs context-broker

"""

SHORT_HELP_LOGS = "Manage container logs."
