from time import sleep

from injector import inject

from commands.db.mongodb_container_manager import MongodbContainerManager
from commands.db.redis_container_manager import RedisContainerManager
from commands.faas.openfaas_container_manager import OpenFaaSContainerManager
from common import Command, CommandGroup, Settings, StdoutSeverity
from common.docker.exceptions import DockerError
from settings.config import LOG_FILE_NAME


class LogsDas(Command):
    name = "das"

    short_help = "Display logs for das."

    help = """
NAME

    logs das - Display logs for the DAS service

SYNOPSIS

    das-cli logs das

DESCRIPTION

    Displays the logs of the DAS service.
    This command reads logs from the log file used by the DAS core process, typically located at `/tmp/das.log`.
    Logs will stream in real-time until the user exits with Ctrl+C.

EXAMPLES

    Display logs of the DAS service:

        das-cli logs das
"""

    def __init__(self) -> None:
        super().__init__()

    def run(self):
        try:
            with open(LOG_FILE_NAME, "r") as file:
                while True:
                    line = file.readline()
                    if not line:
                        sleep(0.1)
                        continue
                    self.stdout(line, new_line=False)
        except KeyboardInterrupt:
            self.stdout("Interrupted. Exiting...", severity=StdoutSeverity.ERROR)
        except FileNotFoundError:
            self.stdout("No logs to show up here", severity=StdoutSeverity.WARNING)


class LogsFaaS(Command):
    name = "faas"

    short_help = "Display logs for OpenFaaS services."

    help = """
NAME

    logs faas - Display logs for the OpenFaaS service

SYNOPSIS

    das-cli logs faas

DESCRIPTION

    Displays the logs of the OpenFaaS service.
    This includes logs related to function execution, deployment events, and potential errors.
    The service must be running for the logs to be available.

EXAMPLES

    Display logs of the OpenFaaS service:

        das-cli logs faas
"""

    @inject
    def __init__(self, settings: Settings) -> None:
        super().__init__()
        self._settings = settings

    def run(self):
        self._settings.raise_on_missing_file()

        openfaas_container_name = self._settings.get("openfaas.container_name")

        try:
            openfaas_service = OpenFaaSContainerManager(openfaas_container_name)
            openfaas_service.logs()
        except DockerError as e:
            self.stdout(
                "You need to run the server with command 'faas start'",
                severity=StdoutSeverity.ERROR,
            )
            raise e


class LogsMongoDb(Command):
    name = "mongodb"

    short_help = "Display logs of the MongoDB service."

    help = """
NAME

    logs mongodb - Display logs for the MongoDB service

SYNOPSIS

    das-cli logs mongodb

DESCRIPTION

    Displays logs generated by the MongoDB container.
    This includes database events such as connections, queries, and internal errors.
    The MongoDB container must be running for logs to be available.

EXAMPLES

    Display logs of the MongoDB service:

        das-cli logs mongodb
"""

    @inject
    def __init__(self, settings: Settings) -> None:
        super().__init__()
        self._settings = settings

    def run(self):
        self._settings.raise_on_missing_file()

        mongodb_container_name = self._settings.get("mongodb.container_name")

        try:
            mongodb_service = MongodbContainerManager(mongodb_container_name)

            mongodb_service.logs()
        except DockerError:
            raise DockerError("You need to run the server with command 'db start'")


class LogsRedis(Command):
    name = "redis"

    short_help = "Display logs for Redis."

    help = """
NAME

    logs redis - Display logs for the Redis service

SYNOPSIS

    das-cli logs redis

DESCRIPTION

    Displays logs generated by the Redis container.
    These logs include cache operations, connections, key access patterns, and error messages.
    The Redis container must be running for logs to be available.

EXAMPLES

    Display logs of the Redis service:

        das-cli logs redis
"""

    @inject
    def __init__(self, settings: Settings) -> None:
        super().__init__()
        self._settings = settings

    def run(self):
        self._settings.raise_on_missing_file()

        redis_container_name = self._settings.get("redis.container_name")

        try:
            redis_service = RedisContainerManager(redis_container_name)

            redis_service.logs()
        except DockerError:
            raise DockerError("You need to run the server with command 'db start'")


class LogsCli(CommandGroup):
    name = "logs"

    short_help = "Manage container logs."

    help = """
NAME

    logs - Manage container logs

SYNOPSIS

    das-cli logs <service>

DESCRIPTION

    Displays logs for services managed by the DAS CLI.
    These logs provide insight into operations, errors, and runtime behavior.

COMMANDS

    das-cli logs das        Logs from the DAS core
    das-cli logs faas       Logs from the OpenFaaS service
    das-cli logs mongodb    Logs from the MongoDB database
    das-cli logs redis      Logs from the Redis cache

EXAMPLES

    Display logs from the DAS core:

        das-cli logs das

    Display logs from the OpenFaaS service:

        das-cli logs faas

    Display logs from MongoDB:

        das-cli logs mongodb

    Display logs from Redis:

        das-cli logs redis
"""

    @inject
    def __init__(
        self,
        logs_das: LogsDas,
        logs_faas: LogsFaaS,
        logs_mongodb: LogsMongoDb,
        logs_redis: LogsRedis,
    ) -> None:
        super().__init__()
        self.add_commands(
            [
                logs_das.command,
                logs_faas.command,
                logs_mongodb.command,
                logs_redis.command,
            ]
        )
