from time import sleep

from injector import inject

from commands.attention_broker.attention_broker_container_manager import AttentionBrokerManager
from commands.db.mongodb_container_manager import MongodbContainerManager
from commands.db.redis_container_manager import RedisContainerManager
from commands.faas.openfaas_container_manager import OpenFaaSContainerManager
from commands.inference_agent.inference_agent_container_manager import (
    InferenceAgentContainerManager,
)
from commands.link_creation_agent.link_creation_agent_container_manager import (
    LinkCreationAgentContainerManager,
)
from commands.query_agent.query_agent_container_manager import QueryAgentContainerManager
from common import Command, CommandGroup, Settings, StdoutSeverity
from common.decorators import ensure_container_running
from settings.config import LOG_FILE_NAME


class LogsDas(Command):
    name = "das"

    short_help = "Display logs for das."

    help = """
NAME

    logs das - Display logs for the DAS service

SYNOPSIS

    das-cli logs das

DESCRIPTION

    Displays the logs of the DAS service.
    This command reads logs from the log file used by the DAS core process, typically located at `/tmp/das.log`.
    Logs will stream in real-time until the user exits with Ctrl+C.

EXAMPLES

    Display logs of the DAS service:

        das-cli logs das
"""

    def __init__(self) -> None:
        super().__init__()

    def run(self):
        try:
            with open(LOG_FILE_NAME, "r") as file:
                while True:
                    line = file.readline()
                    if not line:
                        sleep(0.1)
                        continue
                    self.stdout(line, new_line=False)
        except KeyboardInterrupt:
            self.stdout("Interrupted. Exiting...", severity=StdoutSeverity.ERROR)
        except FileNotFoundError:
            self.stdout("No logs to show up here", severity=StdoutSeverity.WARNING)


class LogsFaaS(Command):
    name = "faas"

    short_help = "Display logs for OpenFaaS services."

    help = """
NAME

    logs faas - Display logs for the OpenFaaS service

SYNOPSIS

    das-cli logs faas

DESCRIPTION

    Displays the logs of the OpenFaaS service.
    This includes logs related to function execution, deployment events, and potential errors.
    The service must be running for the logs to be available.

EXAMPLES

    Display logs of the OpenFaaS service:

        das-cli logs faas
"""

    @inject
    def __init__(
        self,
        settings: Settings,
        openfaas_container_manager: OpenFaaSContainerManager,
    ) -> None:
        super().__init__()
        self._settings = settings
        self._openfaas_container_manager = openfaas_container_manager

    @ensure_container_running(
        ["_openfaas_container_manager"],
        exception_text="OpenFaaS is not running. Please start it with 'das-cli faas start' before viewing logs.",
        verbose=False,
    )
    def run(self):
        self._settings.raise_on_missing_file()
        self._settings.raise_on_schema_mismatch()

        self._openfaas_container_manager.logs()


class LogsMongoDb(Command):
    name = "mongodb"

    short_help = "Display logs of the MongoDB service."

    help = """
NAME

    logs mongodb - Display logs for the MongoDB service

SYNOPSIS

    das-cli logs mongodb

DESCRIPTION

    Displays logs generated by the MongoDB container.
    This includes database events such as connections, queries, and internal errors.
    The MongoDB container must be running for logs to be available.

EXAMPLES

    Display logs of the MongoDB service:

        das-cli logs mongodb
"""

    @inject
    def __init__(
        self,
        settings: Settings,
        mongodb_container_manager: MongodbContainerManager,
    ) -> None:
        super().__init__()
        self._settings = settings
        self._mongodb_container_manager = mongodb_container_manager

    @ensure_container_running(
        ["_mongodb_container_manager"],
        exception_text="MongoDB is not running. Please start it with 'das-cli db start' before viewing logs.",
        verbose=False,
    )
    def run(self):
        self._settings.raise_on_missing_file()
        self._settings.raise_on_schema_mismatch()

        self._mongodb_container_manager.logs()


class LogsRedis(Command):
    name = "redis"

    short_help = "Display logs for Redis."

    help = """
NAME

    logs redis - Display logs for the Redis service

SYNOPSIS

    das-cli logs redis

DESCRIPTION

    Displays logs generated by the Redis container.
    These logs include cache operations, connections, key access patterns, and error messages.
    The Redis container must be running for logs to be available.

EXAMPLES

    Display logs of the Redis service:

        das-cli logs redis
"""

    @inject
    def __init__(
        self,
        settings: Settings,
        redis_container_manager: RedisContainerManager,
    ) -> None:
        super().__init__()
        self._settings = settings
        self._redis_container_manager = redis_container_manager

    @ensure_container_running(
        ["_redis_container_manager"],
        exception_text="Redis is not running. Please start it with 'das-cli db start' before viewing logs.",
        verbose=False,
    )
    def run(self):
        self._settings.raise_on_missing_file()
        self._settings.raise_on_schema_mismatch()

        self._redis_container_manager.logs()


class LogsAttentionBroker(Command):
    name = "attention-broker"

    short_help = "Display logs for the Attention Broker service"

    help = """
'das-cli logs attention-broker' displays the logs of the Attention Broker service.
This command retrieves the logs generated by the Attention Broker, which may include information about message routing, broker events, and errors.

.SH EXAMPLES

Display logs of the Attention Broker service.

$ das-cli logs attention-broker
"""

    @inject
    def __init__(
        self,
        settings: Settings,
        attention_broker_manager: AttentionBrokerManager,
    ) -> None:
        super().__init__()
        self._settings = settings
        self._attention_broker_manager = attention_broker_manager

    @ensure_container_running(
        ["_attention_broker_manager"],
        exception_text="Attention broker is not running. Please start it with 'das-cli attention-broker start' before viewing logs.",
        verbose=False,
    )
    def run(self):
        self._settings.raise_on_missing_file()
        self._settings.raise_on_schema_mismatch()

        self._attention_broker_manager.logs()


class LogsQueryAgent(Command):
    name = "query-agent"

    short_help = "Display logs for the Query Agent service"

    help = """
'das-cli logs query-agent' displays the logs of the Query Agent service.
This command retrieves the logs generated by the Query Agent, which may include information about query processing, agent events, and errors.

.SH EXAMPLES

Display logs of the Query Agent service.

$ das-cli logs query-agent
"""

    @inject
    def __init__(
        self,
        settings: Settings,
        query_agent_container_manager: QueryAgentContainerManager,
    ) -> None:
        super().__init__()
        self._settings = settings
        self._query_agent_container_manager = query_agent_container_manager

    @ensure_container_running(
        ["_query_agent_container_manager"],
        exception_text="Query agent is not running. Please start it with 'das-cli query-agent start' before viewing logs.",
        verbose=False,
    )
    def run(self):
        self._settings.raise_on_missing_file()
        self._settings.raise_on_schema_mismatch()

        self._query_agent_container_manager.logs()


class LogsLinkCreationAgent(Command):
    name = "link-creation-agent"

    short_help = "Display logs for the Link Creation Agent service"

    help = """
'das-cli logs link-creation-agent' displays the logs of the Link Creation Agent service.
This command retrieves the logs generated by the Link Creation Agent, which may include information about link creation processes, agent events, and errors.

.SH EXAMPLES

Display logs of the Link Creation Agent service.

$ das-cli logs link-creation-agent
"""

    @inject
    def __init__(
        self,
        settings: Settings,
        link_creation_container_manager: LinkCreationAgentContainerManager,
    ) -> None:
        super().__init__()
        self._settings = settings
        self._link_creation_container_manager = link_creation_container_manager

    @ensure_container_running(
        ["_link_creation_container_manager"],
        exception_text="Link creation agent is not running. Please start it with 'das-cli link-creation-agent start' before viewing logs.",
        verbose=False,
    )
    def run(self):
        self._settings.raise_on_missing_file()
        self._settings.raise_on_schema_mismatch()

        self._link_creation_container_manager.logs()


class LogsInferenceAgent(Command):
    name = "inference-agent"

    short_help = "Display logs for the Inference Agent service."

    help = """
'das-cli logs inference-agent' displays the logs of the Inference Agent service.
This command retrieves the logs generated by the Inference Agent, which may include information about inference processes, agent events, and errors.

.SH EXAMPLES

Display logs of the Inference Agent service.

$ das-cli logs inference-agent
"""

    @inject
    def __init__(
        self,
        settings: Settings,
        inference_agent_container_manager: InferenceAgentContainerManager,
    ) -> None:
        super().__init__()
        self._settings = settings
        self._inference_agent_container_manager = inference_agent_container_manager

    @ensure_container_running(
        ["_inference_agent_container_manager"],
        exception_text="Inference agent is not running. Please start it with 'das-cli inference-agent start' before viewing logs.",
        verbose=False,
    )
    def run(self):
        self._settings.raise_on_missing_file()
        self._settings.raise_on_schema_mismatch()

        self._inference_agent_container_manager.logs()


class LogsCli(CommandGroup):
    name = "logs"

    short_help = "Manage container logs."

    help = """
NAME

    logs - Manage container logs

SYNOPSIS

    das-cli logs <service>

DESCRIPTION

    Displays logs for services managed by the DAS CLI.
    These logs provide insight into operations, errors, and runtime behavior.

COMMANDS

    das-cli logs das        Logs from the DAS core
    das-cli logs faas       Logs from the OpenFaaS service
    das-cli logs mongodb    Logs from the MongoDB database
    das-cli logs redis      Logs from the Redis cache

EXAMPLES

    Display logs from the DAS core:

        das-cli logs das

    Display logs from the OpenFaaS service:

        das-cli logs faas

    Display logs from MongoDB:

        das-cli logs mongodb

    Display logs from Redis:

        das-cli logs redis
"""

    @inject
    def __init__(
        self,
        logs_das: LogsDas,
        logs_faas: LogsFaaS,
        logs_mongodb: LogsMongoDb,
        logs_redis: LogsRedis,
        logs_attention_broker: LogsAttentionBroker,
        logs_query_agent: LogsQueryAgent,
        logs_link_creation_agent: LogsLinkCreationAgent,
        logs_inference_agent: LogsInferenceAgent,
    ) -> None:
        super().__init__()
        self.add_commands(
            [
                logs_das.command,
                logs_faas.command,
                logs_mongodb.command,
                logs_redis.command,
                logs_attention_broker.command,
                logs_query_agent.command,
                logs_link_creation_agent.command,
                logs_inference_agent.command,
            ]
        )
