FROM ubuntu:22.04

ENV TZ=America/Sao_Paulo \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y build-essential debhelper zlib1g-dev python3-pip python3 gzip

RUN pip3 install pyinstaller==6.3.0

COPY ./requirements.txt ./requirements.txt

RUN pip3 install -r ./requirements.txt

WORKDIR /app/src

ARG EXEC_NAME=main
ENV EXEC_NAME=${EXEC_NAME}

ENTRYPOINT ["sh", "-c", "pyinstaller --paths /app/src main.py -y -F -n $EXEC_NAME --distpath /app/bin"]
