FROM ubuntu:22.04

RUN apt -y update && apt -y install \
    make git jq curl python3 python3-pip \
    && curl -fSs https://get.docker.com | bash \
    && pip3 install --upgrade pip setuptools wheel \
    && apt clean

RUN cd /tmp && \
    git clone --depth=1 --branch v1.11.0 https://github.com/bats-core/bats-core.git && \
    cd bats-core && \
    ./install.sh /usr/local && \
    cd - && \
    rm -rf /tmp/bats-core

WORKDIR /workspace
