FROM ubuntu:22.04

ENV TZ=America/Sao_Paulo \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y build-essential debhelper zlib1g-dev python3-pip python3 gzip

WORKDIR /app/das

COPY . .

RUN pip3 install pyinstaller==6.3.0
RUN pip3 install -r ./src/requirements.txt

ENTRYPOINT ["pyinstaller", "./src/main.py", "-y", "-F", "-n", "das-runner-manager", "--distpath", "/app/das/dist"]
