FROM ubuntu:22.04

ENV USER=ubuntu \
  ROOT_USER=root

RUN apt -y update && apt install -y \
  sudo \
  gh \
  wget \
  curl \
  ca-certificates \
  make \
  jq \
  socat \
  lsof \
  gnupg \
  python3 \
  python3-pip \
  rsync \
  miller \
  fuse-overlayfs \
  lsb-release && \
  useradd -m -s /bin/bash ${USER} && \
  echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
  mkdir -p /opt/actions-runner && chown ${USER}:${USER} /opt/actions-runner && \
  rm -rf /var/lib/apt/lists/*

RUN curl -fSs https://get.docker.com | bash && \
  usermod -aG docker ${USER} && \
  ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /opt/actions-runner

USER ${USER}

ARG TARGETARCH

RUN case "${TARGETARCH}" in \
      amd64) RUNNER_ARCH=x64 ;; \
      arm64) RUNNER_ARCH=arm64 ;; \
      *) echo "Unsupported architecture: ${TARGETARCH}" >&2; exit 1 ;; \
    esac && \
  curl -fL -o actions-runner.tar.gz \
    "https://github.com/actions/runner/releases/download/v2.337.0/actions-runner-linux-${RUNNER_ARCH}-2.337.0.tar.gz" && \
  tar xzf actions-runner.tar.gz && \
  rm actions-runner.tar.gz

USER ${ROOT_USER}

RUN ./bin/installdependencies.sh

COPY scripts/*.sh /opt/actions-runner

RUN chmod +x /opt/actions-runner/*.sh

ENTRYPOINT ["/opt/actions-runner/entrypoint.sh"]

