FROM ubuntu:22.04

ENV TZ=America/Sao_Paulo \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y build-essential debhelper zlib1g-dev python3-pip python3 gzip && \
    curl -fSs https://get.docker.com | bash

WORKDIR /app/das

COPY ./src/requirements.txt ./src/requirements.txt

RUN pip3 install -r ./src/requirements.txt

COPY . .

ENV PYTHONPATH=/app/das/src

ENTRYPOINT [ "python3" ]
CMD [ "src/api_server/main.py" ]
