---
name: DAS Runner Manager Build

on:
  push:
    branches:
      - master

jobs:
  build-binary:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build das-runner-manager binary
        run: make build
        working-directory: das-runner-manager

      - name: Upload das-runner-manager artifact
        uses: actions/upload-artifact@v4
        with:
          name: das-runner-manager
          path: das-runner-manager/dist/*
          if-no-files-found: "error"

  build-github-runner:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: das-runner-manager
          file: das-runner-manager/.docker/Dockerfile.github-runner
          push: true
          tags: levisingnet/github-runner:ubuntu-22.04
