---
name: Run DAS-CLI tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize


jobs:
  build-das-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Dockerfile
        run: docker build -f .docker/Dockerfile.das-toolbox -t das-cli:latest .

      - name: Build das-cli binary
        run: docker run --rm -v "$(pwd)/dist/":/app/das/dist -e DAS_CLI_VERSION=0.1.0 das-cli:latest

      - name: Upload das-cli artifact
        uses: actions/upload-artifact@v4
        with:
          name: das-cli
          path: dist/*

  integration-tests:
    runs-on: ubuntu-latest
    needs: 
      - build-das-cli
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install requirements
        run: sudo apt -y install bats make

      - name: Download das-cli artifact
        uses: actions/download-artifact@v4
        with:
          name: das-cli
          path: packages

      - name: Installing das-cli package
        run: sudo apt -y install $(find . -name *.deb -type f | head -n 1)

      - name: Runnign integration tests
        run: make integration_tests